version: "3"

services:
  minecraft-server-isabel-bruno:
    container_name: minecraft-server-isabel-bruno
    image: itzg/minecraft-server:java17-jdk
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 6G
      VERSION: '1.20.1'
      TYPE: SPIGOT
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data:/data
    networks: 
      - minecraft-server-isabel-bruno

networks:
  minecraft-server-isabel-bruno:
    driver: bridge
