services:
  minecraft-server-isabel-bruno:
    container_name: minecraft-server-isabel-bruno
    image: itzg/minecraft-server
    ports:
      - 25565:25565

    environment:
      EULA: "TRUE"
      MEMORY: 8G
      VERSION: '1.21'
      TYPE: SPIGOT

    tty: true
    stdin_open: true
    restart: unless-stopped

    volumes:
      - ./data:/data
    networks: 
      - minecraft-server-isabel-bruno

networks:
  minecraft-server-isabel-bruno:
    driver: bridge
